[package]
name = "tansu-varint"
edition.workspace = true
version.workspace = true
license.workspace = true


[lints]
workspace = true

[dependencies]
bytes.workspace = true
condtype.workspace = true
thiserror.workspace = true
tokio.workspace = true
