[workspace]
resolver = "2"
members = ["tansu-*"]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.lints.clippy]
# all = "warn"
#pedantic = "warn"

[workspace.lints.rust]
# deprecated_in_future = "warn"
# elided_lifetimes_in_paths = "deny"
# missing_copy_implementations = "warn"
# missing_debug_implementations = "warn"
# non_ascii_idents = "forbid"
# nonstandard_style = "deny"
# rust_2018_idioms = "deny"
# unreachable_pub = "warn"
# unsafe_code = "forbid"
# unused_crate_dependencies = "warn"
# unused_import_braces = "warn"
# unused_labels = "warn"
# unused_lifetimes = "warn"
# unused_qualifications = "warn"
# unused_results = "warn"

[workspace.lints.rustdoc]
# broken_intra_doc_links = "deny"
#private_intra_doc_links = "deny"

[workspace.dependencies]
anyhow = "1.0.79"
async-trait = "0.1.77"
bytes = { version = "1", features = ["serde"] }
clap = { version = "4.5.0", features = ["derive", "env"] }
condtype = "1.3.0"
convert_case = "0.6.0"
crc = "3.0.1"
criterion = { version = "0.5.1", features = ["html_reports"] }
futures = "0.3"
getrandom = "0.2"
glob = "0.3.1"
lazy_static = "1.4.0"
opentelemetry = { version = "0.21.0" }
opentelemetry-jaeger = { version = "0.20.0", features = ["rt-tokio"] }
opentelemetry_sdk = "0.21.2"
prettyplease = "0.2.20"
proc-macro2 = "1.0.81"
quote = "1.0"
rand = "0.8"
regex = "1.10.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
strum = { version = "0.26", features = ["derive"] }
strum_macros = "0.26"
syn = { version = "2.0", features = ["full"] }
tarpc = { version = "0.34", features = ["full"] }
tempfile = "3"
thiserror = "1.0"
time = { version = "0.3.36", features = ["formatting", "macros"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-core = { version = "0.1" }
tracing-subscriber = "0.3"
typetag = "0.2"
ulid = "1.1.3"
url = { version = "2.5.0", features = ["serde"] }
uuid = { version = "1.10.0", features = ["serde", "v4"] }
