---
services:
  c3:
    image: confluentinc/cp-enterprise-control-center:7.6.0
    ports:
      - 9021:9021
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: ${ADVERTISED_LISTENER}
      CONTROL_CENTER_STREAMS_CPRESTPROXY_BOOTSTRAP_SERVERS: ${ADVERTISED_LISTENER}
      CONTROL_CENTER_ID: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_COMMAND_TOPIC_REPLICATION: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_INTERNAL_TOPICS_REPLICATION: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS: 1
      CONTROL_CENTER_STREAMS_CACHE_MAX_BYTES_BUFFERING: 104857600
      CONTROL_CENTER_METRICS_TOPIC_MAX_MESSAGE_BYTES: 8388608
      CONTROL_CENTER_CUB_KAFKA_TIMEOUT: 10
    command:
      - bash
      - -c
      - |
        sleep 5
        /etc/confluent/docker/run
