---
services:
  sr:
    image: confluentinc/cp-schema-registry
    ports:
      - 8081:8081
    container_name: schema-registry
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: ${ADVERTISED_LISTENER}
      SCHEMA_REGISTRY_CUB_KAFKA_TIMEOUT: 300
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 1
