[package]
name = "tansu-proxy"
edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
bytes.workspace = true
clap.workspace = true
tansu-kafka-model = { path = "../tansu-kafka-model" }
tansu-kafka-sans-io = { path = "../tansu-kafka-sans-io" }
thiserror.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
url.workspace = true
