---
name: ci
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - run: |
          echo "RUSTFLAGS=-D errors" >> $GITHUB_ENV
      - run: "echo \"DOCKER_IMAGE_TAGS=\
          ghcr.io/${{github.repository}}:latest\"
          >> $GITHUB_ENV"
      - run: cargo build
      - run: cargo test
      - uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{env.DOCKER_IMAGE_TAGS}}
