---
name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ${{matrix.os}}
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
      - run: cargo build
      - run: cargo fmt --all --check
      - run: cargo clippy --all-targets --all-features
      - run: cargo test
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - run: "echo \"DOCKER_IMAGE_TAGS=\
          ghcr.io/${{github.repository}}:latest\"
          >> $GITHUB_ENV"
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{env.DOCKER_IMAGE_TAGS}}
